services:
  frontend:
    build:
      context: ./frontend
    image: backoffice-frontend:latest
    ports:
      - "3000:3000"
    networks:
      - backoffice-network
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000

  backend:
    build:
      context: ./backend
    image: backoffice-backend:latest
    ports:
      - "5000:5000"  
    networks:
      - backoffice-network

networks:
  backoffice-network:
    driver: bridge
