name: Docker Image CI foor GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the image
        run: |
          docker login --username GuglielmoCerri --password ${{ secrets.GH_PAT }} ghcr.io
          docker build frontend -t ghcr.io/guglielmocerri/backoffice-frontend:latest
          docker build backend -t ghcr.io/guglielmocerri/backoffice-backend:latest
          docker push ghcr.io/guglielmocerri/backoffice-frontend:latest
          docker push ghcr.io/guglielmocerri/backoffice-backend:latest
      